CREATE DATABASE chungcu

USE chungcu

CREATE TABLE NHANVIEN
(
	MANHANVIEN varchar(20) PRIMARY KEY,
	TENNHANVIEN varchar(40) NOT NULL,
	SODIENTHOAI varchar(15) NULL,
	GIOITINH TINYINT,
)

CREATE TABLE CANHO
(
	MACANHO varchar(20) PRIMARY KEY,
	TENCHUHO varchar(50) NOT NULL,
)

CREATE TABLE THIETBI
(
	MATHIETBI varchar(20) PRIMARY KEY,
	TENTHIETBI varchar(50) NOT NULL,
)

CREATE TABLE NV_BT
(
	MANHANVIEN varchar(20) FOREIGN KEY REFERENCES NHANVIEN(MANHANVIEN),
	MATHIETBI varchar(20) FOREIGN KEY REFERENCES THIETBI(MATHIETBI),
	MACANHO varchar(20) FOREIGN KEY REFERENCES CANHO(MACANHO),
	LANTHU int,
	NGAYBAOTRI smalldatetime,
	PRIMARY KEY(MANHANVIEN,MATHIETBI, MACANHO, LANTHU)
)



INSERT INTO NHANVIEN VALUES ('NV01','NGUYEN VAN A',null,1);
INSERT INTO NHANVIEN VALUES ('NV02','NGUYEN VAN B',null,1);
INSERT INTO NHANVIEN VALUES ('NV03','NGUYEN THI C',null,0);

INSERT INTO THIETBI VALUES ('TB01','TIVI');
INSERT INTO THIETBI VALUES ('TB02','Dien Thoai');

INSERT INTO NV_BT VALUES ('NV01','TB01','CH001',1,'11/19/2021');
INSERT INTO NV_BT VALUES ('NV01','TB01','CH001',2,'11/19/2021');
INSERT INTO NV_BT VALUES ('NV01','TB01','CH001',3,'11/19/2021');
INSERT INTO NV_BT VALUES ('NV02','TB02','CH001',1,'11/19/2021');
INSERT INTO NV_BT VALUES ('NV02','TB02','CH001',2,'11/19/2021');